# Generated by Django 3.2.6 on 2021-09-03 16:20

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=twitter.models.generate_unique_code, max_length=8, unique=True)),
                ('user_session', models.CharField(max_length=50, unique=True)),
                ('consumer_key', models.CharField(max_length=75)),
                ('consumer_secret', models.CharField(max_length=75)),
                ('access_token', models.CharField(max_length=75)),
                ('access_token_secret', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
